services:
  vite:
    build:
      context: ./vite
      dockerfile: Dockerfile
    container_name: vite
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./vite/app:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Vite
    restart: unless-stopped
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
volumes:
  db_data:
